[package]
name = "collection_traits"
version = "0.1.0"
edition = "2018"
authors = ["liranxiao"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
